In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv('homeprices.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [6]:
# fill null values
med = df['bedrooms'].median()
med

4.0

In [9]:
df['bedrooms'] = df['bedrooms'].fillna(med)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [10]:
reg = linear_model.LinearRegression()

In [11]:
reg.fit(df[['area','bedrooms','age']],df['price'])

LinearRegression()

In [12]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [13]:
reg.intercept_

221323.00186540443

In [17]:
x_test = [3000,3,40]

In [30]:
reg.predict([x_test])

C:\Users\mtayy\miniconda3\envs\datascience\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

### Let's check

In [31]:
#y = m1x1+m2x2+m3x3+b
m1 = 112.06244194
m2 = 23388.88007794
m3 = -3231.71790863
area = 3000
bedrooms = 3
age = 40
b = 221323.00186540443

In [33]:
price = m1*area+m2*bedrooms+m3*age+b
price

498408.25157402444

In [34]:
reg.predict([[2500,4,5]])

C:\Users\mtayy\miniconda3\envs\datascience\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])