In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import linear_model
from word2number import w2n

In [2]:
df = pd.read_csv('hiring.csv')
df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [6]:
df.isnull().sum()

experience                    2
test_score(out of 10)         1
interview_score(out of 10)    0
salary($)                     0
dtype: int64

In [7]:
df['experience'].fillna('zero', inplace=True)

In [8]:
df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [9]:
df.isnull().sum()

experience                    0
test_score(out of 10)         1
interview_score(out of 10)    0
salary($)                     0
dtype: int64

In [10]:
df['test_score(out of 10)'].unique()

array([ 8.,  6., 10.,  9.,  7., nan])

In [11]:
med = df['test_score(out of 10)'].median()
med

8.0

In [12]:
df['test_score(out of 10)'].fillna(med, inplace=True)

In [13]:
df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [14]:
df.isnull().sum()

experience                    0
test_score(out of 10)         0
interview_score(out of 10)    0
salary($)                     0
dtype: int64

Now convert columns to numeric values

In [15]:
df['experience'] = df['experience'].apply(w2n.word_to_num)

In [16]:
df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000

Let's build the model

In [17]:
reg = linear_model.LinearRegression()

In [18]:
reg.fit(df[['experience', 'test_score(out of 10)', 'interview_score(out of 10)']], df['salary($)'])


LinearRegression()

In [19]:
reg.predict([[2,9,6]])

c:\Users\mtayy\miniconda3\envs\datascience\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53205.96797671])

In [20]:
reg.predict([[12,10,10]])

c:\Users\mtayy\miniconda3\envs\datascience\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92002.18340611])

In [21]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [22]:
reg.intercept_

17737.263464337688

In [24]:
m1 = reg.coef_[0]
m2 = reg.coef_[1]
m3 = reg.coef_[2]
experience = 12
test_score = 10
interview_score = 10
b = reg.intercept_
y = m1*experience + m2*test_score + m3*interview_score + b
y

92002.18340611353