In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_iris

In [2]:
iris = load_iris()

In [3]:
df = pd.DataFrame(iris.data,columns=iris.feature_names)
df['target'] = iris.target
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [4]:
X = df.drop('target',axis=1)
y = df.target

In [5]:
from sklearn.model_selection import cross_val_score

In [6]:
lr = cross_val_score(LogisticRegression(max_iter=10000),X,y)
lr

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [7]:
svc = cross_val_score(SVC(),X,y)
svc

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [8]:
dt = cross_val_score(DecisionTreeClassifier(),X,y)
dt

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])

In [9]:
rf = cross_val_score(RandomForestClassifier(),X,y)
rf

array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])

In [12]:
print(f'LogisticRegression score is {np.mean(lr)}.')
print(f'SVC score is {np.mean(svc)}.')
print(f'DecisonTrees score is {np.mean(dt)}.')
print(f'RandomForestTrees score is {np.mean(rf)}.')

LogisticRegression score is 0.9733333333333334.
SVC score is 0.9666666666666666.
DecisonTrees score is 0.9600000000000002.
RandomForestTrees score is 0.96.


So Logistic Regression gives us the best score for this dataset.