In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_iris

In [2]:
iris = load_iris()

In [3]:
df = pd.DataFrame(data=iris.data,columns = iris.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [4]:
df['target'] = iris.target
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [5]:
X = df.drop('target',axis=1)
y = df.target

In [6]:
from sklearn.model_selection import cross_val_score

In [7]:
lr = cross_val_score(LogisticRegression(max_iter=100),X,y)
lr

c:\Users\mtayy\miniconda3\envs\dataScience\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [8]:
svc = cross_val_score(SVC(),X,y)
svc

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [9]:
dt = cross_val_score(DecisionTreeClassifier(),X,y)
dt

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])

In [16]:
rf = cross_val_score(RandomForestClassifier(n_estimators=200),X,y)
rf

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

In [17]:
print(f'LogisticRegression score is {np.mean(lr)}.')
print(f'SVC score is {np.mean(svc)}.')
print(f'DecisonTrees score is {np.mean(dt)}.')
print(f'RandomForestTrees score is {np.mean(rf)}.')

LogisticRegression score is 0.9733333333333334.
SVC score is 0.9666666666666666.
DecisonTrees score is 0.9600000000000002.
RandomForestTrees score is 0.9666666666666668.
